

# в этом блоке мы описываем контейнеры, которые будут запускаться
services:
  #контейнер с Nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: webserver
    # проброс портов
    ports:
      - "80:80"
    volumes:
       - ./code:/data/mysite.local
    networks:
      - app-network

  #Контейнер с PHP-FPM, назовём его app
  app:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: php # имя будущего образа
    container_name: app # имя контейнера после запуска
    volumes:
       - ./code:/data/mysite.local
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT={REDIS_PORT}
    depends_on:
      - redis
    # command: 
    #   - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    #   - php -r "if (hash_file('sha384', 'composer-setup.php') === 'c8b085408188070d5f52bcfe4ecfbee5f727afa458b2573b8eaaf77b3419b0bf2768dc67c86944da1544f06fa544fd47') { echo 'Installer verified'.PHP_EOL; } else { echo 'Installer corrupt'.PHP_EOL; unlink('composer-setup.php'); exit(1); }"
    #   - php composer-setup.php
    #   - php -r "unlink('composer-setup.php');"
    #   - php composer.phar require predis/predis
  
  redis: 
    image: redis
    container_name: redis
    command: redis-server --appendonly yes
    # ports:
    #   - "81:81"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  memcached:
    image: memcached
    hostname: memcached
    # ports:
    #   - "82:82"
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
    volumes:
      - memcached_data:/data
    networks:
      - app-network

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 83:83
    environment:
      - PMA_ARBITRARY=1

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
  memcached_data: